import { useDeleteChatListener } from "../useEventListeners/useDeleteChatListener";
import { useDeleteReactionListener } from "../useEventListeners/useDeleteReactionListener";
import { useFriendRequestListener } from "../useEventListeners/useFriendRequestListener";
import { useGroupUpdateEventListener } from "../useEventListeners/useGroupUpdateEventListener";
import { useJoinNewChatListener } from "../useEventListeners/useJoinNewChatListener";
import { useMemberRemovedListener } from "../useEventListeners/useMemberRemovedListener";
import { useMessageDeleteListener } from "../useEventListeners/useMessageDeleteListener";
import { useMessageEditListener } from "../useEventListeners/useMessageEditListener";
import { useMessageListener } from "../useEventListeners/useMessageListener";
import { useMessageSeenListener } from "../useEventListeners/useMessageSeenListener";
import { useNewGroupListener } from "../useEventListeners/useNewGroupListener";
import { useNewMemberAddedListener } from "../useEventListeners/useNewMemberAddedListener";
import { useNewReactionListener } from "../useEventListeners/useNewReactionListener";
import { useOfflineListener } from "../useEventListeners/useOfflineListener";
import { useOnlineListener } from "../useEventListeners/useOnlineListener";
import { useOnlineUsersListener } from "../useEventListeners/useOnlineUsersListener";
import { useTypingListener } from "../useEventListeners/useTypingListener";
import { useUnreadMessageListener } from "../useEventListeners/useUnreadMessageListener";
import { useVoteInListener } from "../useEventListeners/useVoteInListener";
import { useVoteOutListener } from "../useEventListeners/useVoteOutListener";

export const useAttachEventListeners = () => {
  useFriendRequestListener();
  useMessageListener();
  useMessageSeenListener();
  useNewGroupListener();
  useUnreadMessageListener();
  useOfflineListener();
  useOnlineListener();
  useTypingListener();
  useNewMemberAddedListener();
  useMessageEditListener();
  useDeleteChatListener();
  useMemberRemovedListener();
  useVoteInListener();
  useVoteOutListener();
  useOnlineUsersListener();
  useMessageDeleteListener();
  useGroupUpdateEventListener();
  useJoinNewChatListener();
  useNewReactionListener();
  useDeleteReactionListener();
};
