import { InitializeIndexedDbWrapper } from "@/components/auth/InitializeIndexedDbWrapper";
import { ModalWrapper } from "@/components/modal/ModalWrapper";
import { ThemeInitializer } from "@/components/theme/ThemeInitializer";
import { SocketProvider } from "@/context/socket.context";
import StoreProvider from "@/lib/client/store/StoreProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Modal root for portals */}
        <div id="modal-root"></div>
        <StoreProvider>
          <SocketProvider>
            <Toaster />
            <InitializeIndexedDbWrapper />
            <ThemeInitializer />
            <ModalWrapper />
            {children}
          </SocketProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
